/* Generated By:JJTree: Do not edit this line. AST_var.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class AST_var extends SimpleNode {
  public AST_var(int id) {
    super(id);
  }

  public AST_var(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new AST_var(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new AST_var(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c343a01b36c81de5884c4e29b6c5b279 (do not edit this line) */
