/* Generated By:JJTree: Do not edit this line. ASTattlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTattlist extends SimpleNode {
  public ASTattlist(int id) {
    super(id);
  }

  public ASTattlist(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTattlist(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTattlist(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59d6f843b1f7f9958ef8eeda38d43fd1 (do not edit this line) */
