/* Generated By:JJTree: Do not edit this line. ASTbasefont.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTbasefont extends SimpleNode {
  public ASTbasefont(int id) {
    super(id);
  }

  public ASTbasefont(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTbasefont(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTbasefont(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c71d1677ecf6df708c1f673d569029b8 (do not edit this line) */
