/* Generated By:JJTree: Do not edit this line. ASTbig.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTbig extends SimpleNode {
  public ASTbig(int id) {
    super(id);
  }

  public ASTbig(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTbig(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTbig(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7b18799ccb0388f44e863498cd6543eb (do not edit this line) */
