/* Generated By:JJTree: Do not edit this line. ASTcite.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTcite extends SimpleNode {
  public ASTcite(int id) {
    super(id);
  }

  public ASTcite(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTcite(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTcite(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b6a5fa3b46bb7b2eff1164033c4a500 (do not edit this line) */
