/* Generated By:JJTree: Do not edit this line. ASTcenter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTcenter extends SimpleNode {
  public ASTcenter(int id) {
    super(id);
  }

  public ASTcenter(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTcenter(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTcenter(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0e3a85ae343102c21d42fc68a4292cde (do not edit this line) */
