/* Generated By:JJTree: Do not edit this line. ASTcode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTcode extends SimpleNode {
  public ASTcode(int id) {
    super(id);
  }

  public ASTcode(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTcode(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTcode(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d6795d2fa3ed85762d0a588c8a7dd746 (do not edit this line) */
