/* Generated By:JJTree: Do not edit this line. ASTcaption.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTcaption extends SimpleNode {
  public ASTcaption(int id) {
    super(id);
  }

  public ASTcaption(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTcaption(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTcaption(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75df7b3a080cbfd89c2a428a351b9150 (do not edit this line) */
