/* Generated By:JJTree: Do not edit this line. ASTdfn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTdfn extends SimpleNode {
  public ASTdfn(int id) {
    super(id);
  }

  public ASTdfn(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTdfn(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTdfn(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1093dda4379565cfd813969e86a9362a (do not edit this line) */
