/* Generated By:JJTree: Do not edit this line. ASTform.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTform extends SimpleNode {
  public ASTform(int id) {
    super(id);
  }

  public ASTform(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTform(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTform(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7fc401fb442616c5e945823e50068e25 (do not edit this line) */
