/* Generated By:JJTree: Do not edit this line. ASThr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASThr extends SimpleNode {
  public ASThr(int id) {
    super(id);
  }

  public ASThr(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASThr(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASThr(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1efd1de0f5fab397db3df1c60dee0a85 (do not edit this line) */
