/* Generated By:JJTree: Do not edit this line. ASTh1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTh1 extends SimpleNode {
  public ASTh1(int id) {
    super(id);
  }

  public ASTh1(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTh1(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTh1(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a1db7f8f63a936c96839d7409d176b3 (do not edit this line) */
