/* Generated By:JJTree: Do not edit this line. ASTh2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTh2 extends SimpleNode {
  public ASTh2(int id) {
    super(id);
  }

  public ASTh2(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTh2(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTh2(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=40eeeabee5efff8291996b5f38ca20da (do not edit this line) */
