/* Generated By:JJTree: Do not edit this line. ASTh6.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTh6 extends SimpleNode {
  public ASTh6(int id) {
    super(id);
  }

  public ASTh6(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTh6(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTh6(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4392282d108950e689ca8d2da9358bcb (do not edit this line) */
