/* Generated By:JJTree: Do not edit this line. ASTi.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTi extends SimpleNode {
  public ASTi(int id) {
    super(id);
  }

  public ASTi(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTi(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTi(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a3f2d71d8b8ce59d7874f6319bef591b (do not edit this line) */
