/* Generated By:JJTree: Do not edit this line. ASTli.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTli extends SimpleNode {
  public ASTli(int id) {
    super(id);
  }

  public ASTli(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTli(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTli(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95f37238c70a63e49536ef4182c6af61 (do not edit this line) */
