/* Generated By:JJTree: Do not edit this line. ASTmenu.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTmenu extends SimpleNode {
  public ASTmenu(int id) {
    super(id);
  }

  public ASTmenu(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTmenu(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTmenu(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e4afbd86a745a6343dc4161aea264b8 (do not edit this line) */
