/* Generated By:JJTree: Do not edit this line. ASTmeta.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTmeta extends SimpleNode {
  public ASTmeta(int id) {
    super(id);
  }

  public ASTmeta(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTmeta(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTmeta(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8aad3f53389792d2f61b1392c375dfc9 (do not edit this line) */
