/* Generated By:JJTree: Do not edit this line. ASToption.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASToption extends SimpleNode {
  public ASToption(int id) {
    super(id);
  }

  public ASToption(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASToption(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASToption(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=21e727070a659a64401721753755ad13 (do not edit this line) */
