/* Generated By:JJTree: Do not edit this line. ASTsamp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTsamp extends SimpleNode {
  public ASTsamp(int id) {
    super(id);
  }

  public ASTsamp(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTsamp(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTsamp(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2b78f4c4eeec519fd9c41dd85eb3c390 (do not edit this line) */
