/* Generated By:JJTree: Do not edit this line. ASTsup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTsup extends SimpleNode {
  public ASTsup(int id) {
    super(id);
  }

  public ASTsup(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTsup(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTsup(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cf8e900e0b8140730197d846091b58a7 (do not edit this line) */
