/* Generated By:JJTree: Do not edit this line. ASTtextarea.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTtextarea extends SimpleNode {
  public ASTtextarea(int id) {
    super(id);
  }

  public ASTtextarea(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTtextarea(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTtextarea(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=013c75b303232cdd13422635aba3043c (do not edit this line) */
