/* Generated By:JJTree: Do not edit this line. ASTth.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTth extends SimpleNode {
  public ASTth(int id) {
    super(id);
  }

  public ASTth(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTth(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTth(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bef28c8a34e25a29dfee8d28a4ea9a13 (do not edit this line) */
