/* Generated By:JJTree: Do not edit this line. ASTtt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTtt extends SimpleNode {
  public ASTtt(int id) {
    super(id);
  }

  public ASTtt(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTtt(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTtt(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fdd1e838e24fa337542c8fad2294c743 (do not edit this line) */
