/* Generated By:JJTree: Do not edit this line. ASTtitle.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTtitle extends SimpleNode {
  public ASTtitle(int id) {
    super(id);
  }

  public ASTtitle(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTtitle(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTtitle(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=50483823b798819e08972e64b79439e9 (do not edit this line) */
