/* Generated By:JJTree: Do not edit this line. ASTtable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTtable extends SimpleNode {
  public ASTtable(int id) {
    super(id);
  }

  public ASTtable(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTtable(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTtable(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=40cd4ef9729bfcecc79cf484d349618a (do not edit this line) */
