/* Generated By:JJTree: Do not edit this line. ASTu.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package html;

public
class ASTu extends SimpleNode {
  public ASTu(int id) {
    super(id);
  }

  public ASTu(html32 p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTu(id);
  }

  public static Node jjtCreate(html32 p, int id) {
    return new ASTu(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(html32Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1e85df60e3fdedbae500d8e94b612cd6 (do not edit this line) */
