/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package factory.codegen;

import javax.swing.JOptionPane;

/**
 *
 * @author John Mwai
 */
public class TestHarness extends javax.swing.JFrame {

    ExtensionInformation c;
    CodeGeneraror cg;

    /**
     * Creates new form TestHarness
     */
    public TestHarness() {
        initComponents();

//        c = new CodeGeneraror.ExtensionInformation();
//        c.setAuthor("John Mwai");
//        c.setAppName("Bravia_Cart");
//
//        cg = new CodeGeneraror();
//        cg.context = c;
//
//
//        //we are creating things in admin
//        cg.admin = true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCodeGeneratorAction = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox();
        jTextFieldViewName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonAdd = new javax.swing.JRadioButton();
        jRadioButtonRemove = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldJoomlaDir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "controller", "model", "helper", "view", "script", "table" }));

        jTextFieldViewName.setText("test");

        jLabel1.setText("Name");

        buttonGroupCodeGeneratorAction.add(jRadioButtonAdd);
        jRadioButtonAdd.setSelected(true);
        jRadioButtonAdd.setText("Add");

        buttonGroupCodeGeneratorAction.add(jRadioButtonRemove);
        jRadioButtonRemove.setText("Remove");

        jButton1.setText("Execute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("JoomlaDir");

        jTextFieldJoomlaDir.setText("C:\\wamp\\www\\my_joomla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldViewName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonAdd)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jRadioButtonRemove)))
                    .addComponent(jTextFieldJoomlaDir, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldJoomlaDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldViewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAdd)
                    .addComponent(jRadioButtonRemove))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        cg.setJoomlaDir(
//                jTextFieldJoomlaDir.getText());
//        String viewName = jTextFieldViewName.getText();
//        if (jRadioButtonAdd.isSelected()) {
//
//            if (jComboBox1.getSelectedItem().toString().equals("model")) {
//                try {
//                    if (cg.addModel(viewName, null, null)) {
//                        JOptionPane.showMessageDialog(rootPane,
//                                "Model succsssfully added.");
//                    }
//                } catch (Exception exception) {
//                    JOptionPane.showMessageDialog(rootPane,
//                            exception.getMessage());
//                    exception.printStackTrace();
//                }
//            }
//        } else if (jRadioButtonRemove.isSelected()) {
//            if (jComboBox1.getSelectedItem().toString().equals("model")) {
//                try {
//                    if (cg.removeModel(viewName)) {
//                        JOptionPane.showMessageDialog(rootPane,
//                                "Model succsssfully removed.");
//                    }else{
//                        JOptionPane.showMessageDialog(rootPane,
//                                "Model could not be removed.");
//                    }
//                } catch (Exception exception) {
//                    JOptionPane.showMessageDialog(rootPane,
//                            exception.getMessage());
//                    exception.printStackTrace();
//                }
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestHarness.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestHarness.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestHarness.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestHarness.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestHarness().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCodeGeneratorAction;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonAdd;
    private javax.swing.JRadioButton jRadioButtonRemove;
    private javax.swing.JTextField jTextFieldJoomlaDir;
    private javax.swing.JTextField jTextFieldViewName;
    // End of variables declaration//GEN-END:variables
}
