/* Generated By:JJTree: Do not edit this line. ASTClassBodyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTClassBodyDeclaration extends SimpleNode {
  public ASTClassBodyDeclaration(int id) {
    super(id);
  }

  public ASTClassBodyDeclaration(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTClassBodyDeclaration(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTClassBodyDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9d9d00c3a98fc5d89cf66413e5f816e3 (do not edit this line) */
