/* Generated By:JJTree: Do not edit this line. ASTInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTInitializer extends SimpleNode {
  public ASTInitializer(int id) {
    super(id);
  }

  public ASTInitializer(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTInitializer(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTInitializer(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=415861b9f34315446b595ea517701441 (do not edit this line) */
