/* Generated By:JJTree: Do not edit this line. ASTInterfaceMemberDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTInterfaceMemberDeclaration extends SimpleNode {
  public ASTInterfaceMemberDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceMemberDeclaration(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTInterfaceMemberDeclaration(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTInterfaceMemberDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a45925d2f3a8aabba0406be966e52c78 (do not edit this line) */
