/* Generated By:JJTree: Do not edit this line. ASTNestedInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTNestedInterfaceDeclaration extends SimpleNode {
  public ASTNestedInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTNestedInterfaceDeclaration(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTNestedInterfaceDeclaration(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTNestedInterfaceDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6663404d91fb089d315d8a22f92d3aa8 (do not edit this line) */
