/* Generated By:JJTree: Do not edit this line. ASTNestedClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTNestedClassDeclaration extends SimpleNode {
  public ASTNestedClassDeclaration(int id) {
    super(id);
  }

  public ASTNestedClassDeclaration(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTNestedClassDeclaration(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTNestedClassDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=35254f6e3d3a184aeaf31ad24c17b7fb (do not edit this line) */
