/* Generated By:JJTree: Do not edit this line. ASTResultType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTResultType extends SimpleNode {
  public ASTResultType(int id) {
    super(id);
  }

  public ASTResultType(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTResultType(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTResultType(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0001499319202402cfd54b2963d534be (do not edit this line) */
