/* Generated By:JJTree: Do not edit this line. ASTUnmodifiedClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTUnmodifiedClassDeclaration extends SimpleNode {
  public ASTUnmodifiedClassDeclaration(int id) {
    super(id);
  }

  public ASTUnmodifiedClassDeclaration(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTUnmodifiedClassDeclaration(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTUnmodifiedClassDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=305eb0adb74469a4bd9d9b48e2bbbc7d (do not edit this line) */
