/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjava;

public
class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(JavaParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableDeclaratorId(id);
  }

  public static Node jjtCreate(JavaParser p, int id) {
    return new ASTVariableDeclaratorId(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=271a12243de684dd9bdad5bf47222ed6 (do not edit this line) */
