/* Generated By:JJTree: Do not edit this line. ASTArrayLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTArrayLiteral extends SimpleNode {
  public ASTArrayLiteral(int id) {
    super(id);
  }

  public ASTArrayLiteral(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTArrayLiteral(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTArrayLiteral(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f7744c1d26bf707bee48bdde09980c12 (do not edit this line) */
