/* Generated By:JJTree: Do not edit this line. ASTCaseGroups.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTCaseGroups extends SimpleNode {
  public ASTCaseGroups(int id) {
    super(id);
  }

  public ASTCaseGroups(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTCaseGroups(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTCaseGroups(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c3d703e7b351032ed5c9aabb1f9e7280 (do not edit this line) */
