/* Generated By:JJTree: Do not edit this line. ASTCompositeReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTCompositeReference extends SimpleNode {
  public ASTCompositeReference(int id) {
    super(id);
  }

  public ASTCompositeReference(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTCompositeReference(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTCompositeReference(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=15fe22a18fa6913f416bf08af580fd73 (do not edit this line) */
