/* Generated By:JJTree: Do not edit this line. ASTCaseGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTCaseGroup extends SimpleNode {
  public ASTCaseGroup(int id) {
    super(id);
  }

  public ASTCaseGroup(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTCaseGroup(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTCaseGroup(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e3a5a6392f130590a6e67e8c6aee834 (do not edit this line) */
