/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTDoStatement extends SimpleNode {
  public ASTDoStatement(int id) {
    super(id);
  }

  public ASTDoStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTDoStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTDoStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d7959347833269105dc38ee62bd503cd (do not edit this line) */
