/* Generated By:JJTree: Do not edit this line. ASTExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTExpressionList extends SimpleNode {
  public ASTExpressionList(int id) {
    super(id);
  }

  public ASTExpressionList(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTExpressionList(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTExpressionList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d99d5db05119aabc2ba7b6672d91952 (do not edit this line) */
