/* Generated By:JJTree: Do not edit this line. ASTEmptyExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTEmptyExpression extends SimpleNode {
  public ASTEmptyExpression(int id) {
    super(id);
  }

  public ASTEmptyExpression(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTEmptyExpression(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTEmptyExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95971a61f92a6c07259f4208f7d05e50 (do not edit this line) */
