/* Generated By:JJTree: Do not edit this line. ASTExpressionStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTExpressionStatement extends SimpleNode {
  public ASTExpressionStatement(int id) {
    super(id);
  }

  public ASTExpressionStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTExpressionStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTExpressionStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7938d73541fe59d87e61ba94e4261897 (do not edit this line) */
