/* Generated By:JJTree: Do not edit this line. ASTForVarInStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTForVarInStatement extends SimpleNode {
  public ASTForVarInStatement(int id) {
    super(id);
  }

  public ASTForVarInStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTForVarInStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTForVarInStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2ca817d174bbf8d1b28862ac8f9654f6 (do not edit this line) */
