/* Generated By:JJTree: Do not edit this line. ASTFinallyClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTFinallyClause extends SimpleNode {
  public ASTFinallyClause(int id) {
    super(id);
  }

  public ASTFinallyClause(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFinallyClause(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTFinallyClause(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=87c4c02d26dea606a3a015d30f1c2f27 (do not edit this line) */
