/* Generated By:JJTree: Do not edit this line. ASTForVarStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTForVarStatement extends SimpleNode {
  public ASTForVarStatement(int id) {
    super(id);
  }

  public ASTForVarStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTForVarStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTForVarStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5123c10398dbe95716bd2613ff0e2179 (do not edit this line) */
