/* Generated By:JJTree: Do not edit this line. ASTImportStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTImportStatement extends SimpleNode {
  public ASTImportStatement(int id) {
    super(id);
  }

  public ASTImportStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTImportStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTImportStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eaca23668dad1c58b722a87e446339da (do not edit this line) */
