/* Generated By:JJTree: Do not edit this line. ASTLabelledStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTLabelledStatement extends SimpleNode {
  public ASTLabelledStatement(int id) {
    super(id);
  }

  public ASTLabelledStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLabelledStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTLabelledStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=405b138d0db2b60ee55978f99576d13c (do not edit this line) */
