/* Generated By:JJTree: Do not edit this line. ASTObjectLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTObjectLiteral extends SimpleNode {
  public ASTObjectLiteral(int id) {
    super(id);
  }

  public ASTObjectLiteral(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTObjectLiteral(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTObjectLiteral(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2e135a0f22b404f624fefdeaf293b6aa (do not edit this line) */
