/* Generated By:JJTree: Do not edit this line. ASTPropertyIdentifierReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTPropertyIdentifierReference extends SimpleNode {
  public ASTPropertyIdentifierReference(int id) {
    super(id);
  }

  public ASTPropertyIdentifierReference(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTPropertyIdentifierReference(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTPropertyIdentifierReference(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0bb72e79373e9667dc2dc0175f511e08 (do not edit this line) */
