/* Generated By:JJTree: Do not edit this line. ASTPropertyValueReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTPropertyValueReference extends SimpleNode {
  public ASTPropertyValueReference(int id) {
    super(id);
  }

  public ASTPropertyValueReference(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTPropertyValueReference(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTPropertyValueReference(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1bb46e8c4014cd9a6fded2c3b6457d34 (do not edit this line) */
