/* Generated By:JJTree: Do not edit this line. ASTThrowStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTThrowStatement extends SimpleNode {
  public ASTThrowStatement(int id) {
    super(id);
  }

  public ASTThrowStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTThrowStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTThrowStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa81282622b9b783de1f16804f4e46cc (do not edit this line) */
