/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTVariableDeclarationList extends SimpleNode {
  public ASTVariableDeclarationList(int id) {
    super(id);
  }

  public ASTVariableDeclarationList(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableDeclarationList(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTVariableDeclarationList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9e480b789586d1c8663f0248b36be6cd (do not edit this line) */
