/* Generated By:JJTree: Do not edit this line. ASTVariableStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTVariableStatement extends SimpleNode {
  public ASTVariableStatement(int id) {
    super(id);
  }

  public ASTVariableStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTVariableStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d5016c6fb221d7c18bd4f6209b813e14 (do not edit this line) */
