/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarationNoIn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTVariableDeclarationNoIn extends SimpleNode {
  public ASTVariableDeclarationNoIn(int id) {
    super(id);
  }

  public ASTVariableDeclarationNoIn(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableDeclarationNoIn(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTVariableDeclarationNoIn(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c5c154bbbff10a068e89cdffaf43b573 (do not edit this line) */
