/* Generated By:JJTree: Do not edit this line. ASTWithStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ecmascript;

public
class ASTWithStatement extends SimpleNode {
  public ASTWithStatement(int id) {
    super(id);
  }

  public ASTWithStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTWithStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
    return new ASTWithStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e5e07ca1ecd3be938c4132648f239346 (do not edit this line) */
