/* Generated By:JJTree: Do not edit this line. ASTattrib.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTattrib extends SimpleNode {
  public ASTattrib(int id) {
    super(id);
  }

  public ASTattrib(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTattrib(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTattrib(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f1ed6f5a22ff17233e15cfc32e97329 (do not edit this line) */
