/* Generated By:JJTree: Do not edit this line. ASTcss_import.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTcss_import extends SimpleNode {
  public ASTcss_import(int id) {
    super(id);
  }

  public ASTcss_import(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTcss_import(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTcss_import(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c42fc5c4645a35823d011fd6832bc658 (do not edit this line) */
