/* Generated By:JJTree: Do not edit this line. ASTmedia.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTmedia extends SimpleNode {
  public ASTmedia(int id) {
    super(id);
  }

  public ASTmedia(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTmedia(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTmedia(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5d55b17a53cd34d76d308783709fcd7 (do not edit this line) */
