/* Generated By:JJTree: Do not edit this line. ASTmedia_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTmedia_list extends SimpleNode {
  public ASTmedia_list(int id) {
    super(id);
  }

  public ASTmedia_list(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTmedia_list(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTmedia_list(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c7833bb489a3836db2943ca81401ef8b (do not edit this line) */
