/* Generated By:JJTree: Do not edit this line. ASTpage.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTpage extends SimpleNode {
  public ASTpage(int id) {
    super(id);
  }

  public ASTpage(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTpage(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTpage(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c27e6ebae579924c300ad879b3e0aa2 (do not edit this line) */
