/* Generated By:JJTree: Do not edit this line. ASTpseudo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTpseudo extends SimpleNode {
  public ASTpseudo(int id) {
    super(id);
  }

  public ASTpseudo(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTpseudo(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTpseudo(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a89d9bf7dd9c00b997dc5883f479fac (do not edit this line) */
