/* Generated By:JJTree: Do not edit this line. ASTruleset.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTruleset extends SimpleNode {
  public ASTruleset(int id) {
    super(id);
  }

  public ASTruleset(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTruleset(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTruleset(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e3249ba4d8fcfdbefa07080771931a75 (do not edit this line) */
