/* Generated By:JJTree: Do not edit this line. ASTstylesheet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTstylesheet extends SimpleNode {
  public ASTstylesheet(int id) {
    super(id);
  }

  public ASTstylesheet(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTstylesheet(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTstylesheet(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5985412fd1279b55df39de5e99b77b91 (do not edit this line) */
