/* Generated By:JJTree: Do not edit this line. ASTsingleStyle.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTsingleStyle extends SimpleNode {
  public ASTsingleStyle(int id) {
    super(id);
  }

  public ASTsingleStyle(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTsingleStyle(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTsingleStyle(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0dac611b4592cc40e9c0222e7cea9437 (do not edit this line) */
