/* Generated By:JJTree: Do not edit this line. ASTsimple_selector.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTsimple_selector extends SimpleNode {
  public ASTsimple_selector(int id) {
    super(id);
  }

  public ASTsimple_selector(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTsimple_selector(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTsimple_selector(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a82bc94d6a5f7014e2996e548579a9b9 (do not edit this line) */
