/* Generated By:JJTree: Do not edit this line. ASTunary_operator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package css;

public
class ASTunary_operator extends SimpleNode {
  public ASTunary_operator(int id) {
    super(id);
  }

  public ASTunary_operator(CSSParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTunary_operator(id);
  }

  public static Node jjtCreate(CSSParser p, int id) {
    return new ASTunary_operator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(CSSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dfb349c665c94800e9b3478495befe45 (do not edit this line) */
