/* Generated By:JavaCC: Do not edit this line. CSSParserVisitor.java Version 5.0 */
package css;

public interface CSSParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTerror_skipto node, Object data);
  public Object visit(ASTstylesheet node, Object data);
  public Object visit(ASTsingleStyle node, Object data);
  public Object visit(ASTcss_import node, Object data);
  public Object visit(ASTmedia node, Object data);
  public Object visit(ASTmedia_list node, Object data);
  public Object visit(ASTpage node, Object data);
  public Object visit(ASTpageID node, Object data);
  public Object visit(ASToperator_expr node, Object data);
  public Object visit(ASTcombinator node, Object data);
  public Object visit(ASTunary_operator node, Object data);
  public Object visit(ASTruleset node, Object data);
  public Object visit(ASTselector node, Object data);
  public Object visit(ASTsimple_selector node, Object data);
  public Object visit(ASTclass_ident node, Object data);
  public Object visit(ASTelement_name node, Object data);
  public Object visit(ASTattrib node, Object data);
  public Object visit(ASTpseudo node, Object data);
  public Object visit(ASTdeclaration node, Object data);
  public Object visit(ASTexpr node, Object data);
  public Object visit(ASTterm node, Object data);
  public Object visit(ASTfunction_expr node, Object data);
}
/* JavaCC - OriginalChecksum=0ef1b3dd792779482a561804f17ed571 (do not edit this line) */
