/* Generated By:JavaCC: Do not edit this line. CSSParserTreeConstants.java Version 5.0 */
package css;

public interface CSSParserTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTSTYLESHEET = 1;
  public int JJTSINGLESTYLE = 2;
  public int JJTCSS_IMPORT = 3;
  public int JJTMEDIA = 4;
  public int JJTMEDIA_LIST = 5;
  public int JJTPAGE = 6;
  public int JJTPAGEID = 7;
  public int JJTOPERATOR_EXPR = 8;
  public int JJTCOMBINATOR = 9;
  public int JJTUNARY_OPERATOR = 10;
  public int JJTRULESET = 11;
  public int JJTSELECTOR = 12;
  public int JJTSIMPLE_SELECTOR = 13;
  public int JJTCLASS_IDENT = 14;
  public int JJTELEMENT_NAME = 15;
  public int JJTATTRIB = 16;
  public int JJTPSEUDO = 17;
  public int JJTDECLARATION = 18;
  public int JJTEXPR = 19;
  public int JJTTERM = 20;
  public int JJTFUNCTION_EXPR = 21;


  public String[] jjtNodeName = {
    "error_skipto",
    "stylesheet",
    "singleStyle",
    "css_import",
    "media",
    "media_list",
    "page",
    "pageID",
    "operator_expr",
    "combinator",
    "unary_operator",
    "ruleset",
    "selector",
    "simple_selector",
    "class_ident",
    "element_name",
    "attrib",
    "pseudo",
    "declaration",
    "expr",
    "term",
    "function_expr",
  };
}
/* JavaCC - OriginalChecksum=8401a1ec1299f354ca511393ed9a8b43 (do not edit this line) */
