package factory.packager;

import com.fuscard.commons.FileUtils;
import com.fuscard.commons.GUIUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractButton;
import javax.swing.text.SimpleAttributeSet;

/**
 *
 * @author John Mwai
 */
public class Packager extends javax.swing.JFrame {

    private PackagerApp app = new PackagerApp();
    private LinkedList<Component> deactivatables = new LinkedList<>();
    SimpleAttributeSet defaultAttributeSet;
    SimpleAttributeSet errorAttributeSet;
    SimpleAttributeSet alertAttributeSet;
    SimpleAttributeSet successAttributeSet;
    SimpleAttributeSet dataAttributeSet;

    /**
     * Creates new form Packager
     */
    public Packager() {
        initComponents();
        prepareAttributeSets();
        setComponentsToDisable();
        deactivate();
        write("Welcome to Joomla Extension Packager!\nVersion : $t. Author: $t\n",
                "1.0", "John Mwai");
        writeAttLn("Please log in to use this software.");
        prepareGUI();
    }

    private void prepareGUI() {
        jTextFieldManifestLocation.setText(app.getLastManifestLocation(this));
    }

    private void prepareAttributeSets() {
        defaultAttributeSet = new SimpleAttributeSet();
        GUIUtils.modifyAttributeSet(defaultAttributeSet,
                GUIUtils.TextAttributes.FontSize, 12);
        GUIUtils.modifyAttributeSet(defaultAttributeSet,
                GUIUtils.TextAttributes.FontFamily, "monospaced");
        GUIUtils.modifyAttributeSet(defaultAttributeSet,
                GUIUtils.TextAttributes.ForeGround, new Color(45, 45, 115));
        GUIUtils.modifyAttributeSet(defaultAttributeSet,
                GUIUtils.TextAttributes.Bold, false);

        errorAttributeSet = new SimpleAttributeSet(defaultAttributeSet);
        GUIUtils.modifyAttributeSet(errorAttributeSet,
                GUIUtils.TextAttributes.ForeGround, Color.RED);
        GUIUtils.modifyAttributeSet(errorAttributeSet,
                GUIUtils.TextAttributes.Bold, true);

        successAttributeSet = new SimpleAttributeSet(defaultAttributeSet);
        GUIUtils.modifyAttributeSet(successAttributeSet,
                GUIUtils.TextAttributes.ForeGround, Color.GREEN.darker());
        GUIUtils.modifyAttributeSet(successAttributeSet,
                GUIUtils.TextAttributes.Bold, true);

        alertAttributeSet = new SimpleAttributeSet(defaultAttributeSet);
        GUIUtils.modifyAttributeSet(alertAttributeSet,
                GUIUtils.TextAttributes.ForeGround, Color.GRAY);
        GUIUtils.modifyAttributeSet(alertAttributeSet,
                GUIUtils.TextAttributes.BackGround, Color.YELLOW.brighter());
        GUIUtils.modifyAttributeSet(alertAttributeSet,
                GUIUtils.TextAttributes.Bold, true);
        GUIUtils.modifyAttributeSet(alertAttributeSet,
                GUIUtils.TextAttributes.Underline, true);

        dataAttributeSet = new SimpleAttributeSet(defaultAttributeSet);
        GUIUtils.modifyAttributeSet(dataAttributeSet,
                GUIUtils.TextAttributes.ForeGround, new Color(140, 140, 140));//
        GUIUtils.modifyAttributeSet(dataAttributeSet,
                GUIUtils.TextAttributes.BackGround, new Color(234, 244,
                255));//[234,244,255]
    }

    private void setComponentsToDisable() {
        deactivatables.add(jButtonAddSource);
        deactivatables.add(jButtonBrowseManifest);
        deactivatables.add(jButtonPackage);
        deactivatables.add(jButtonRemoveSource);
        Enumeration<AbstractButton> elements = buttonGroupVersionModifier.
                                                       getElements();
        while(elements.hasMoreElements()){
            deactivatables.add(elements.nextElement());
        }
        deactivatables.add(jCheckBoxDeleteDir);
        deactivatables.add(jCheckBoxIncrementVersion);
        deactivatables.add(jCheckBoxZipFolder);
        deactivatables.add(jTextFieldManifestLocation);
        deactivatables.add(jTextFieldMinimumVersion);
        deactivatables.add(jTableSources);
        deactivatables.add(jSpinnerLevelOfRelease);
        deactivatables.add(jButtonLoadManifest);
    }

    private void activate() {
        for (Component c : deactivatables) {
            c.setEnabled(true);
        }
    }

    private void deactivate() {
        for (Component c : deactivatables) {
            c.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDatabaseConnection = new javax.swing.JDialog(this);
        ;
        jPanel3 = new javax.swing.JPanel();
        jTextFieldUsrName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonLogIn = new javax.swing.JButton();
        jTextFieldPword = new javax.swing.JPasswordField();
        jCheckBoxSavePword = new javax.swing.JCheckBox();
        jButtonCancelLogIn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDBUrl = new javax.swing.JTextField();
        jFileChooserMain = new javax.swing.JFileChooser();
        buttonGroupVersionModifier = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxDeleteDir = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerLevelOfRelease = new javax.swing.JSpinner();
        jCheckBoxIncrementVersion = new javax.swing.JCheckBox();
        jTextFieldMinimumVersion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jCheckBoxZipFolder = new javax.swing.JCheckBox();
        jButtonBrowseManifest = new javax.swing.JButton();
        jTextFieldManifestLocation = new javax.swing.JTextField();
        jButtonPackage = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSources = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButtonAddSource = new javax.swing.JButton();
        jButtonRemoveSource = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneManifest = new javax.swing.JTextPane();
        jButtonLoadManifest = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogIn = new javax.swing.JMenuItem();
        jMenuItemLogOff = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jDialogDatabaseConnection.setTitle("Database connection form");

        jPanel3.setBackground(new java.awt.Color(226, 218, 201));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 207, 167)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Fill in your credentials to connect to the database");

        jButtonLogIn.setText("Log in");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });

        jTextFieldPword.setColumns(15);
        jTextFieldPword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPwordKeyReleased(evt);
            }
        });

        jCheckBoxSavePword.setText("Save password");
        jCheckBoxSavePword.setToolTipText("Caution! Your password will be saved in plain text in the configuration file!");

        jButtonCancelLogIn.setText("Cancel");
        jButtonCancelLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelLogInActionPerformed(evt);
            }
        });

        jLabel4.setLabelFor(jTextFieldDBUrl);
        jLabel4.setText("Database URL");

        jLabel5.setLabelFor(jTextFieldUsrName);
        jLabel5.setText("User Name");

        jLabel6.setLabelFor(jTextFieldPword);
        jLabel6.setText("Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jCheckBoxSavePword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonLogIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelLogIn))
                            .addComponent(jTextFieldDBUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jTextFieldUsrName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldDBUrl, jTextFieldUsrName});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDBUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldUsrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogIn)
                    .addComponent(jCheckBoxSavePword)
                    .addComponent(jButtonCancelLogIn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogDatabaseConnectionLayout = new javax.swing.GroupLayout(jDialogDatabaseConnection.getContentPane());
        jDialogDatabaseConnection.getContentPane().setLayout(jDialogDatabaseConnectionLayout);
        jDialogDatabaseConnectionLayout.setHorizontalGroup(
            jDialogDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDatabaseConnectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogDatabaseConnectionLayout.setVerticalGroup(
            jDialogDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDatabaseConnectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFileChooserMain.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        jFileChooserMain.setApproveButtonText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Joomla Extension Packager");
        setIconImage(getFormIcon());

        jPanel2.setBackground(new java.awt.Color(226, 218, 201));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 207, 167)));

        jLabel3.setText("Manifest");

        jCheckBoxDeleteDir.setText("Delete directory if exists");
        jCheckBoxDeleteDir.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(204, 196, 183));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Level of release");

        jCheckBoxIncrementVersion.setText("Increment version");
        jCheckBoxIncrementVersion.setOpaque(false);

        jLabel1.setText("Minimum version");

        buttonGroupVersionModifier.add(jRadioButton1);
        jRadioButton1.setText("alpha");
        jRadioButton1.setOpaque(false);

        buttonGroupVersionModifier.add(jRadioButton2);
        jRadioButton2.setText("beta");
        jRadioButton2.setOpaque(false);

        buttonGroupVersionModifier.add(jRadioButton3);
        jRadioButton3.setText("RC");
        jRadioButton3.setOpaque(false);

        buttonGroupVersionModifier.add(jRadioButton4);
        jRadioButton4.setText("pl");
        jRadioButton4.setOpaque(false);

        buttonGroupVersionModifier.add(jRadioButton5);
        jRadioButton5.setText("dev");
        jRadioButton5.setOpaque(false);

        buttonGroupVersionModifier.add(jRadioButton6);
        jRadioButton6.setText("other");
        jRadioButton6.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMinimumVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBoxIncrementVersion)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerLevelOfRelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMinimumVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxIncrementVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerLevelOfRelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton6)
                .addContainerGap())
        );

        jCheckBoxZipFolder.setText("zip folder");
        jCheckBoxZipFolder.setOpaque(false);

        jButtonBrowseManifest.setText("browse");
        jButtonBrowseManifest.setToolTipText("Please browse to the manifest file of the extension you want to package within your Joomla installation.");
        jButtonBrowseManifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseManifestActionPerformed(evt);
            }
        });

        jButtonPackage.setText("Package");

        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel6.setBackground(new java.awt.Color(204, 196, 183));

        jTableSources.setBackground(new java.awt.Color(255, 246, 227));
        jTableSources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Location", "Name", "Type", "Target location"
            }
        ));
        jScrollPane3.setViewportView(jTableSources);

        jButtonAddSource.setText("Add source");

        jButtonRemoveSource.setText("Remove");

        jButton5.setText("browse");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButtonAddSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoveSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonAddSource)
                .addComponent(jButtonRemoveSource)
                .addComponent(jButton5))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setTopComponent(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 196, 183));

        log.setEditable(false);
        log.setBackground(new java.awt.Color(255, 246, 227));
        jScrollPane1.setViewportView(log);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Log", jPanel4);

        jScrollPane4.setViewportView(jTextPaneManifest);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Manifest", jPanel5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jSplitPane1.setRightComponent(jPanel7);

        jButtonLoadManifest.setText("Load");
        jButtonLoadManifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadManifestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxDeleteDir)
                        .addGap(29, 29, 29)
                        .addComponent(jCheckBoxZipFolder)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPackage))
                    .addComponent(jSplitPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldManifestLocation)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBrowseManifest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLoadManifest)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxDeleteDir)
                    .addComponent(jCheckBoxZipFolder))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldManifestLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonBrowseManifest)
                    .addComponent(jButtonLoadManifest))
                .addGap(13, 13, 13)
                .addComponent(jSplitPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPackage)
                .addGap(6, 6, 6))
        );

        jMenu1.setText("File");

        jMenuItemLogIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogIn.setText("Log in");
        jMenuItemLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogInActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogIn);

        jMenuItemLogOff.setText("Log off");
        jMenuItemLogOff.setEnabled(false);
        jMenuItemLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOffActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogOff);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Quit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");

        jMenuItem1.setText("Clear log");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogInActionPerformed
        app.displayLoginDialog(this, true);
    }//GEN-LAST:event_jMenuItemLogInActionPerformed

    private void jButtonCancelLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelLogInActionPerformed
        app.displayLoginDialog(this, false);
    }//GEN-LAST:event_jButtonCancelLogInActionPerformed

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        logInAction(true);
    }//GEN-LAST:event_jButtonLogInActionPerformed

    private void jTextFieldPwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPwordKeyReleased
        jCheckBoxSavePword.setSelected(app.getPasswordChanged(
                jTextFieldPword.getText()));
    }//GEN-LAST:event_jTextFieldPwordKeyReleased

    private void jMenuItemLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOffActionPerformed
        logInAction(false);
    }//GEN-LAST:event_jMenuItemLogOffActionPerformed

    private void jButtonBrowseManifestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseManifestActionPerformed
        selectManifest();
    }//GEN-LAST:event_jButtonBrowseManifestActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        log.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonLoadManifestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadManifestActionPerformed
        loadManifest(jTextFieldManifestLocation.getText().trim());
    }//GEN-LAST:event_jButtonLoadManifestActionPerformed

    private void loadManifest(String location) {
        File f = new File(location);
        //confirm that we got an xml file
        String extension = FileUtils.getExtension(f);
        if (extension != null && "xml".equals(extension.toLowerCase())
                && f.isFile()) {
            writeSucLn("File accepted.");
            app.saveManifestLocation(f.getPath());
            writeln("Application will now read manifest file.");
            app.readManifest(this, f);
        } else {
            writeErrLn(
                    "The file you entered is not a valid XML file. Please try again.");
        }
    }

    private void selectManifest() {
        File f;
        String location = jTextFieldManifestLocation.getText();
        if (location == null || "".equals(location)) {
            jTextFieldManifestLocation.
                    setText(app.getLastManifestLocation(this));
        }
        f = FileUtils.selectFile(this, jTextFieldManifestLocation,
                jFileChooserMain,
                new String[]{"xml"}, "XML file");

        if (f == null) {
            writeln("You have canceled manifest selection.");
            return;
        }
        write("You have selected manifest file: $t\n", f.getPath());
        loadManifest(f.getPath());
    }

    private void logInAction(boolean onOrOff) {
        if (onOrOff) {
            if (app.logIn(this)) {
                activate();
                jMenuItemLogIn.setEnabled(false);
                jMenuItemLogOff.setEnabled(true);
            }
        } else {
            if (app.logOff(this)) {
                deactivate();
                jMenuItemLogIn.setEnabled(true);
                jMenuItemLogOff.setEnabled(false);
            }
        }
    }

    final void write(String s) {
        GUIUtils.putStyledText(log,
                s,
                defaultAttributeSet);
    }

    final void writeErr(String s) {
        GUIUtils.putStyledText(log,
                s,
                errorAttributeSet);
    }

    final void writeErrLn(String s) {
        writeErr(s + "\n");
    }

    final void writeAtt(String s) {
        GUIUtils.putStyledText(log,
                s,
                alertAttributeSet);
    }

    final void writeAttLn(String s) {
        writeAtt(s + "\n");
    }

    final void writeDat(String s) {
        GUIUtils.putStyledText(log,
                s,
                dataAttributeSet);
    }

    final void writeDatLn(String s) {
        writeDat(s + "\n");
    }

    final void writeSuc(String s) {
        GUIUtils.putStyledText(log,
                s,
                successAttributeSet);
    }

    final void writeSucLn(String s) {
        writeSuc(s + "\n");
    }

    final void writeln(String s) {
        write(s + "\n");
    }

    final void write(String string, String... s) {
        Pattern rule = Pattern.compile("\\$[a-z]");
        Matcher m = rule.matcher(string);
        int lastEnd = 0;
        int count = 0;
        while (m.find()) {
            count++;
        }
        if (count != s.length) {
            throw new IllegalArgumentException("Malformed rules.");
        }
        count = 0;
        m.reset();

        while (m.find()) {
            write(string.substring(lastEnd, m.start()));
            String g = s[count];
            count++;
            switch (m.group()) {
                case "$d":
                    write(g);
                    break;
                case "$e":
                    writeErr(g);
                    break;
                case "$t":
                    writeDat(g);
                    break;
                case "$a":
                    writeAtt(g);
                    break;
                case "$s":
                    writeSuc(g);
                    break;
            }
            lastEnd = m.end();
        }
        if (lastEnd < string.length()) {
            String sub = string.substring(lastEnd, string.length());
            write(sub);
        }

    }

    private Image getFormIcon() {
        return GUIUtils.createImage(GUIUtils.FUSCARD_LOGO_48X48_RELATIVE_PATH);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException |
                IllegalAccessException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Packager.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Packager().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupVersionModifier;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAddSource;
    private javax.swing.JButton jButtonBrowseManifest;
    private javax.swing.JButton jButtonCancelLogIn;
    private javax.swing.JButton jButtonLoadManifest;
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonPackage;
    private javax.swing.JButton jButtonRemoveSource;
    private javax.swing.JCheckBox jCheckBoxDeleteDir;
    private javax.swing.JCheckBox jCheckBoxIncrementVersion;
    javax.swing.JCheckBox jCheckBoxSavePword;
    private javax.swing.JCheckBox jCheckBoxZipFolder;
    javax.swing.JDialog jDialogDatabaseConnection;
    private javax.swing.JFileChooser jFileChooserMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemLogIn;
    private javax.swing.JMenuItem jMenuItemLogOff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinnerLevelOfRelease;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableSources;
    javax.swing.JTextField jTextFieldDBUrl;
    javax.swing.JTextField jTextFieldManifestLocation;
    private javax.swing.JTextField jTextFieldMinimumVersion;
    javax.swing.JPasswordField jTextFieldPword;
    javax.swing.JTextField jTextFieldUsrName;
    javax.swing.JTextPane jTextPaneManifest;
    javax.swing.JTextPane log;
    // End of variables declaration//GEN-END:variables
}
