/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTBitwiseAndExpression extends SimpleNode {
  public ASTBitwiseAndExpression(int id) {
    super(id);
  }

  public ASTBitwiseAndExpression(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTBitwiseAndExpression(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTBitwiseAndExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a6f7bc9a69bde514a481a981bf91f302 (do not edit this line) */
