/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTBitwiseOrExpression extends SimpleNode {
  public ASTBitwiseOrExpression(int id) {
    super(id);
  }

  public ASTBitwiseOrExpression(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTBitwiseOrExpression(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTBitwiseOrExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=56ab66c8a27c5318913b0cd00a534fd4 (do not edit this line) */
