/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTBitwiseXorExpression extends SimpleNode {
  public ASTBitwiseXorExpression(int id) {
    super(id);
  }

  public ASTBitwiseXorExpression(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTBitwiseXorExpression(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTBitwiseXorExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1bb67cf567c58a7a67a567e843e6da8f (do not edit this line) */
