/* Generated By:JJTree: Do not edit this line. ASTClassInstantiation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTClassInstantiation extends SimpleNode {
  public ASTClassInstantiation(int id) {
    super(id);
  }

  public ASTClassInstantiation(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTClassInstantiation(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTClassInstantiation(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=39587b53e6445e43db3f740c3a71b41d (do not edit this line) */
