/* Generated By:JJTree: Do not edit this line. ASTDefineStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTDefineStatement extends SimpleNode {
  public ASTDefineStatement(int id) {
    super(id);
  }

  public ASTDefineStatement(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTDefineStatement(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTDefineStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=56ad9b6c730135b7099736c779636bfe (do not edit this line) */
