/* Generated By:JJTree: Do not edit this line. ASTEmbeddedHtml.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTEmbeddedHtml extends SimpleNode {
  public ASTEmbeddedHtml(int id) {
    super(id);
  }

  public ASTEmbeddedHtml(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTEmbeddedHtml(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTEmbeddedHtml(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0853f2f69ad243d3cb47a3ab55e63804 (do not edit this line) */
