/* Generated By:JJTree: Do not edit this line. ASTExpressionStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTExpressionStatement extends SimpleNode {
  public ASTExpressionStatement(int id) {
    super(id);
  }

  public ASTExpressionStatement(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTExpressionStatement(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTExpressionStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6e3bf8478ab3b360ec2b6764fe142345 (do not edit this line) */
