/* Generated By:JJTree: Do not edit this line. ASTHtmlBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTHtmlBlock extends SimpleNode {
  public ASTHtmlBlock(int id) {
    super(id);
  }

  public ASTHtmlBlock(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTHtmlBlock(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTHtmlBlock(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9e4f6ce76141716471bd6b17d0c704d5 (do not edit this line) */
