/* Generated By:JJTree: Do not edit this line. ASTInterfaceMembers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTInterfaceMembers extends SimpleNode {
  public ASTInterfaceMembers(int id) {
    super(id);
  }

  public ASTInterfaceMembers(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTInterfaceMembers(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTInterfaceMembers(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f0442703e3fde9628aa416afac14598 (do not edit this line) */
