/* Generated By:JJTree: Do not edit this line. ASTLogicalTextXorExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTLogicalTextXorExpression extends SimpleNode {
  public ASTLogicalTextXorExpression(int id) {
    super(id);
  }

  public ASTLogicalTextXorExpression(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLogicalTextXorExpression(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTLogicalTextXorExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1b3495145b4200f5358f38ae8f2c74c (do not edit this line) */
