/* Generated By:JJTree: Do not edit this line. ASTLogical_Or_Expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTLogical_Or_Expression extends SimpleNode {
  public ASTLogical_Or_Expression(int id) {
    super(id);
  }

  public ASTLogical_Or_Expression(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLogical_Or_Expression(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTLogical_Or_Expression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1c841426f0401e235d4f4a22bd237670 (do not edit this line) */
