/* Generated By:JJTree: Do not edit this line. ASTMemberDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTMemberDeclaration extends SimpleNode {
  public ASTMemberDeclaration(int id) {
    super(id);
  }

  public ASTMemberDeclaration(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTMemberDeclaration(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTMemberDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f9757f65e6e4e1d341fe609e8c1bfc9b (do not edit this line) */
