/* Generated By:JJTree: Do not edit this line. ASTPrefixIncDecExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTPrefixIncDecExpression extends SimpleNode {
  public ASTPrefixIncDecExpression(int id) {
    super(id);
  }

  public ASTPrefixIncDecExpression(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTPrefixIncDecExpression(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTPrefixIncDecExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c632e2d5cf48d7b6a6d448d30ec704df (do not edit this line) */
