/* Generated By:JJTree: Do not edit this line. ASTParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTParameterList extends SimpleNode {
  public ASTParameterList(int id) {
    super(id);
  }

  public ASTParameterList(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTParameterList(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTParameterList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=663105448092c8ee18bc5940c9eca9ff (do not edit this line) */
