/* Generated By:JJTree: Do not edit this line. ASTPhpPage.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTPhpPage extends SimpleNode {
  public ASTPhpPage(int id) {
    super(id);
  }

  public ASTPhpPage(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTPhpPage(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTPhpPage(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e22a173da694d0ffc916c63a9d35ca1b (do not edit this line) */
