/* Generated By:JJTree: Do not edit this line. ASTTryBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package php;

public
class ASTTryBlock extends SimpleNode {
  public ASTTryBlock(int id) {
    super(id);
  }

  public ASTTryBlock(PHP p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTryBlock(id);
  }

  public static Node jjtCreate(PHP p, int id) {
    return new ASTTryBlock(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(PHPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2d4a12ac57d20e749ce8bb537623cc15 (do not edit this line) */
